MonEtabv1.4/src/EtabV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('student/', include("student.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('base/', include("base.urls")),
    path('login/', include('login.urls')),
    path('', include('api.urls')),
    path('report/', include('report.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

MonEtabv1.4/src/api/urls.py
from django.urls import path, include
from rest_framework import routers


from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from .viewsets.student_viewset import StudentViewset
from .viewsets.teacher_viewset import TeacherViewset
from .viewsets.appSetting_viewset import AppSettingViewset
from .viewsets.school_viewset import SchoolViewset
from .viewsets.role_user_viewset import Role_user_viewset
from .viewsets.student_card_viewset import StudentCardViewset
from .viewsets.absence_viewset import AbsenseViewset
from .viewsets.custom_user_viewset import CustomUserViewset
from .viewsets.address_viewset import Address_Viewset
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenObtainSlidingView,
    TokenRefreshSlidingView,
    TokenVerifyView,
)

app_name = 'api'


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'students', StudentViewset)
router.register(r'teachers', TeacherViewset)
router.register(r'AppSettings', AppSettingViewset)
router.register(r'school', SchoolViewset)
router.register(r'rolUser', Role_user_viewset)
router.register(r'studentCard', StudentCardViewset)
router.register(r'absence', AbsenseViewset)
router.register(r'customUser', CustomUserViewset)
router.register(r'Adress',Address_Viewset)



urlpatterns = [
    path('', include(router.urls)),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('token-sliding/', TokenObtainSlidingView.as_view(), name='token_obtain_sliding'),
    path('token-sliding/refresh/', TokenRefreshSlidingView.as_view(), name='token_refresh_sliding'),

    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
   
    
 ]

MonEtabv1.4/src/student/urls.py
from django.urls import path
from .views.student_view import index,add, update, delete, check_setting
from .views.absence_view import add_abs,list_abs, update_abs 
from .views.studentCards_view import add_card, list_card, update_student_card



app_name="student"
urlpatterns = [

    path('', check_setting, name='check_setting'),

    path('index', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-student"),
    path('delete/<int:id>',delete,name="delete-student"),

    path('add_abs',add_abs,name="add_abs"),
    path('list_abs',list_abs,name="list_abs"),
    path('update_abs/<int:id>',update_abs,name="update_absence"),

    path('add_card',add_card,name="add_card"),
    path('list_card',list_card,name="list_card"),
    path('update_student_card/<int:id>', update_student_card, name='update_student_card')
]

MonEtabv1.4/src/student/models/absence_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel

# Create your models here.
class AbsenceModel(DateTimeModel):
    student = models.ForeignKey('student.StudentModel', on_delete=models.CASCADE, related_name="student_ids")
    absence_date = models.DateField()
    absence_number = models.IntegerField()

    class Meta:
        verbose_name = "Absence"
        verbose_name_plural = "Absences"

MonEtabv1.4/src/student/models/studentCards_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel

class StudentCardsModel(DateTimeModel):
    student = models.ForeignKey('student.StudentModel', on_delete=models.CASCADE)
    reference = models.CharField(max_length=50)
    issue_date = models.DateField()
    expiration_date = models.DateField()

    class Meta:
        verbose_name = "StudentCards"
        verbose_name_plural = "StudentCards"

MonEtabv1.4/src/student/models/student_model.py
from django.db import models
from base.models.helpers.person_model import PersonModel


class StudentModel(PersonModel):

    matricule = models.CharField(max_length=20)
    phone_number_father = models.CharField(max_length=20)
    
    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"

    def __str__(self):
        return f"{self.matricule}: {self.first_name}"

MonEtabv1.4/src/student/forms/absence_form.py
from django import forms
from student.models.absence_model import AbsenceModel


class AbsenceForm(forms.ModelForm):
    class Meta:
        model = AbsenceModel
        fields = "__all__"
        widgets={
            'absence_date':forms.DateInput(attrs={'type':'date'}),
        }
        

MonEtabv1.4/src/student/forms/studentCards_form.py
from django import forms
from student.models.studentCards_model import StudentCardsModel


class StudentCardFoms(forms.ModelForm):
    class Meta:
        model = StudentCardsModel
        fields = "__all__"
        widgets={
            'issue_date':forms.DateInput(attrs={'type':'date'}),
            'expiration_date':forms.DateInput(attrs={'type':'date'}),
            
        }
       

MonEtabv1.4/src/student/forms/student_form.py
from django import forms
from student.models.student_model import StudentModel
from base.models.helpers.person_model import PersonModel

class StudentFoms(forms.ModelForm):
    class Meta:
        model = StudentModel
        fields = "__all__"
        widgets={
            'birthday':forms.DateInput(attrs={'type':'date'}),
            'gender' :forms.RadioSelect(choices=PersonModel.GENDER_CHOICES),
        }

MonEtabv1.4/src/student/views/absence_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from student.models.absence_model import AbsenceModel
from student.forms.absence_form import AbsenceForm



@login_required()
def add_abs(request):
    context={"title":"Ajout Absence"}

    if request.method == "POST":
        print(request.POST)
        absence_form =AbsenceForm(request.POST)
        context["absence_form"] = absence_form
        if absence_form.is_valid():
            print("form is valid")
            print(absence_form.cleaned_data)
            absence_form.save()
            return redirect('student:list_abs')
        else:
            return render(request,"student/absence.html")

    # context={'elev_form':elev_form}
    absence_form = AbsenceForm()
    context["absence_form"] = absence_form

    return render(request,"student/absence.html",context)


@login_required()
def list_abs(request):

    absences = AbsenceModel.objects.all()

    absence_count = AbsenceModel.objects.count()

    context = {
        'absences':absences,
        'absence_count':absence_count 
    }

    return render(request, "student/list_abs.html", context)


@login_required()
def update_abs(request,id):

    absence = AbsenceModel.objects.get(id = id)
    
    context={"title":"Modifier Absence"}

    if request.method == "POST":
        print(request.POST)
        absence_form =AbsenceForm(request.POST, instance = absence)
        context["absence_form"] = absence_form
        if absence_form.is_valid():
            print("form is valid")
            print(absence_form.cleaned_data)
            absence_form.save()
            return redirect('student:list_abs')
        else:
            return render(request,"student/absence.html")

    # context={'elev_form':elev_form}
    absence_form = AbsenceForm( instance = absence)

    context["absence_form"] = absence_form

    return render(request,"student/absence.html",context)

MonEtabv1.4/src/student/views/studentCards_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from student.forms.studentCards_form import StudentCardFoms
from student.models.studentCards_model import StudentCardsModel


@login_required()
def add_card(request):
    context={"title":"Carte Etudiant"}

    if request.method == "POST":
        print(request.POST)
        student_card_form =StudentCardFoms(request.POST)
        context["student_card_form"] = student_card_form
        if student_card_form.is_valid():
            print("form is valid")
            print(student_card_form.cleaned_data)
            student_card_form.save()
            return redirect('student:list_card')
        else:
            return render(request,"student/studentCards.html")


    student_card_form = StudentCardFoms()

    context["student_card_form"] = student_card_form

    return render(request,"student/studentCards.html",context)


@login_required()
def list_card(request):
    studentCardss = StudentCardsModel.objects.all()
    carte_count = StudentCardsModel.objects.count()
    context = {
        'studentCardss':studentCardss,
        'carte_count':carte_count
        
    }
    return render(request, "student/list_card.html", context)


@login_required()
def update_student_card(request, id):

    student_card = StudentCardsModel.objects.get(id = id)

    context={"title":"Carte Etudiant"}

    if request.method == "POST":
        print(request.POST)
        student_card_form =StudentCardFoms(request.POST, instance = student_card)
        context["student_card_form"] = student_card_form
        if student_card_form.is_valid():
            print("form is valid")
            print(student_card_form.cleaned_data)
            student_card_form.save()
            return redirect('student:list_card')
        else:
            return render(request,"student/studentCards.html")


    student_card_form = StudentCardFoms(instance = student_card)
    
    context["student_card_form"] = student_card_form

    return render(request,"student/studentCards.html",context)

MonEtabv1.4/src/student/views/student_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from student.forms.student_form import StudentFoms
from student.models.student_model import StudentModel
from user.models.appSetting_model import AppSettingModel


@login_required
def index(request):

    search_field = request.GET.get('search')

    if search_field:

        students = StudentModel.objects.filter(last_name__icontains = search_field)
        student_count = StudentModel.objects.count()

        context = {
            'students': students,
            'search_fields': search_field
        }
    else:
        students = StudentModel.objects.all()
        student_count = StudentModel.objects.count()
        context = {
            'students':students,
            'student_count': student_count
            
        }

    return render(request, "student/index.html", context)


@login_required()
def add(request):
    context={"title":"Ajouter Eleve"}

    if request.method == "POST":
        print(request.POST)
        form =StudentFoms(request.POST)
        context["form"] = form
        if form.is_valid():
            print("form is valid")
            print(form.cleaned_data)
            form.save()
            return redirect('student:index')
        else:
            return render(request,"student/add.html")

    # context={'elev_form':elev_form}
    form = StudentFoms()
    context["form"] = form

    return render(request,"student/add.html",context)


@login_required()
def update(request, id ):
    student = StudentModel.objects.get(id=id)

    context = {"title":"Modifier eleve"}


    if request.method == "POST":
        form = StudentFoms(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student:index')
        
    form = StudentFoms(instance = student)

    context["form"] = form

    return render(request,"student/add.html",context)


@login_required()
def delete(request ,id):
    student = StudentModel.objects.get(id = id)
    student.delete()
    return redirect('student:index')



def check_setting(request):
    app_setting  = AppSettingModel.objects.all()

    if not app_setting:
        return redirect('user:appS')
    else:
        return redirect('user:check_school')

MonEtabv1.4/src/templates/student/absence.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'student:list_abs' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}

             {{ absence_form }}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}

MonEtabv1.4/src/templates/student/add.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'student:index' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}

             {{form}}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}

MonEtabv1.4/src/templates/student/index.html
{% extends 'base.html' %}
{% load static %}




{% block content %}

<!-- Main Content -->
<div class="flex-1 p-6">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-semibold">Élèves : {{ student_count }}</h1>
    <a href="{% url 'student:add' %}" class="flex items-center text-blue-500 hover:text-blue-700">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24"
        stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
      </svg>
      Nouvel élève
    </a>
  </div>
  <div>
    <form get="GET" action="">
      <input type="text" value="{{ search_fields }}" placeholder="Rechercher....." name="search">
      <input type="submit" value="Rechercher">
    </form>
  </div> <br>
  <div class="bg-white p-6 rounded-lg shadow overflow-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Date de Naissance
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Prénom
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Nom
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Telephone
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Url picture
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Genre
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Matricule
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Téléphone du pére
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Adresse
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            User
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Etablissement
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for student in students %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">{{student.birthday}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.first_name}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.last_name}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.phone_number}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.url_picture}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.gender}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.matricule}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.phone_number_father}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.adress.street}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.user.pseudo}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{student.user.school.name}}</td>
          <td class="px-6 py-4 whitespace-nowrap">
            <a href="{% url 'student:update-student' student.id %}"
              class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded">
              Modifier
            </a>
            <button class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded ml-2">
              <a class="button" href="#popup{{student.id }}">Supprimer</a>
            </button>
          </td>
          <div id="popup{{student.id }}" class="overlay">
            <div class="popup">
              <h2>ATTENTION !!!</h2>
              <a class="close" href="#">&times;</a>
              <div class="content">
                Voulez-vous supprimer cet élève ?
                <div>
                  <a href="#" class="bg-green-500 hover:bg-green-600 text-white font-bold py-1 px-4 rounded">Non</a>
                  <a href="{% url 'student:delete-student' student.id %}"
                    class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded">Oui</a>
                </div>
              </div>
            </div>
          </div>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

MonEtabv1.4/src/templates/student/list_abs.html
{% extends 'base.html' %}
{% load static %}

    

 
{% block content %}

      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">Listes des absences : {{ absence_count }}</h1>
          <a
            href="{% url 'student:add_abs' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouvelle Absence
          </a>
        </div>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nombre d'absence
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date d'absence
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Matricule
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Prenoms
                </th>
                
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for absence in absences %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.absence_number}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.absence_date}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.student.matricule}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.student.last_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.student.first_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <a
                  href="{% url 'student:update_absence' absence.id %}"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Modifier
                  </a>
                </td>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}

MonEtabv1.4/src/templates/student/list_card.html
{% extends 'base.html' %}
{% load static %}

    

 
{% block content %}

      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">Listes des cartes : {{ carte_count }}</h1>
          <a
            href="{% url 'student:add_card' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouvelle Carte d'étudiant
          </a>
        </div>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Numéro de la carte
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date de création
                </th>
                <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
              >
                Date d'expiration
              </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Matricule
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Prenoms
                </th>
                
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for studentCards in studentCardss %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.reference}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.issue_date}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.expiration_date}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.student.matricule}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.student.last_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.student.first_name}}</td>

                <td class="px-6 py-4 whitespace-nowrap">
                  <a
                  href="{% url 'student:update_student_card' studentCards.id %}"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Modifier
                  </a>
                </td>
                
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}

MonEtabv1.4/src/templates/student/studentCards.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'student:list_card' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}

             {{ student_card_form }}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}