MonEtabv1.4/src/EtabV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('student/', include("student.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('base/', include("base.urls")),
    path('login/', include('login.urls')),
    path('', include('api.urls')),
    path('report/', include('report.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

MonEtabv1.4/src/api/urls.py
from django.urls import path, include
from rest_framework import routers


from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from .viewsets.student_viewset import StudentViewset
from .viewsets.teacher_viewset import TeacherViewset
from .viewsets.appSetting_viewset import AppSettingViewset
from .viewsets.school_viewset import SchoolViewset
from .viewsets.role_user_viewset import Role_user_viewset
from .viewsets.student_card_viewset import StudentCardViewset
from .viewsets.absence_viewset import AbsenseViewset
from .viewsets.custom_user_viewset import CustomUserViewset
from .viewsets.address_viewset import Address_Viewset
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenObtainSlidingView,
    TokenRefreshSlidingView,
    TokenVerifyView,
)

app_name = 'api'


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'students', StudentViewset)
router.register(r'teachers', TeacherViewset)
router.register(r'AppSettings', AppSettingViewset)
router.register(r'school', SchoolViewset)
router.register(r'rolUser', Role_user_viewset)
router.register(r'studentCard', StudentCardViewset)
router.register(r'absence', AbsenseViewset)
router.register(r'customUser', CustomUserViewset)
router.register(r'Adress',Address_Viewset)



urlpatterns = [
    path('', include(router.urls)),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('token-sliding/', TokenObtainSlidingView.as_view(), name='token_obtain_sliding'),
    path('token-sliding/refresh/', TokenRefreshSlidingView.as_view(), name='token_refresh_sliding'),

    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
   
    
 ]

MonEtabv1.4/src/user/urls.py
from django.urls import path
from .views.user_view import index, add, update, check_user, sign_out, desable_user
from .views.appSetting_view import  appS, check_setting, edition_setting
from .views.school_view import school, check_school, edition
from .views.roleUser_view import role, index_role, role_update, check_role_user


app_name="user"
urlpatterns = [

    path('', check_setting, name='check_setting'),

    path('dashboard/', index,name="index"),
    path('desable/<int:id>', desable_user, name='desable_user'),
    path('checkuser', check_user, name='check_user'),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-user"),

    path('checkschool', check_school, name='check_school'),
    path('school',school,name="school"),
    path('edition_school', edition, name='edition_school'),

    path('role',role,name="role"),
    path('checkroleuser', check_role_user, name='check_role_user'),
    path('index_role',index_role,name="index_role"),
    path('update_user_role/<int:id>',role_update, name='update_user_role'),
    

    path('appS',appS,name="appS"),
    path('edittion',edition_setting,name="edition_setting"),


    
    path('signout', sign_out, name='sign_out'),
    
    #path('delete/<int:id>',delete,name="delete-student"),
]

MonEtabv1.4/src/user/models/appSetting_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel


# Create your models here.
class AppSettingModel(DateTimeModel):
    smtp_server = models.CharField(max_length=50) 
    smtp_port = models.IntegerField()
    smtp_username = models.CharField(max_length=50)
    smtp_password = models.CharField(max_length=50)

    class Meta:
        verbose_name = "AppSetting"
        verbose_name_plural = "AppSettings"

    def __str__(self):
        return f"{self.smtp_server}, {self.smtp_username}"

MonEtabv1.4/src/user/models/custom_user_model.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUserModel(AbstractUser):
    roleUser = models.ManyToManyField('user.RoleUserModel', default=1)
    school = models.ForeignKey('user.SchoolModel', on_delete=models.CASCADE,default=1)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return f"{self.username}, {self.school}"

MonEtabv1.4/src/user/models/roleUser_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel


# Create your models here.
class RoleUserModel(DateTimeModel):

    role = models.CharField(max_length=50)

    class Meta:
        verbose_name = "RoleUser"
        verbose_name_plural = "RoleUsers"

    def __str__(self):
        return f"{self.role}"

MonEtabv1.4/src/user/models/school_model.py
from django.db import models
from base.models.helpers.named_date_time_model import NamedDateTimeModel


# Create your models here.
class SchoolModel(NamedDateTimeModel):

    appSetting = models.OneToOneField('user.AppSettingModel', on_delete=models.CASCADE, related_name="user_app_setting_ids")
    url_logo = models.CharField(max_length=50)

    class Meta:
        verbose_name = "School"
        verbose_name_plural = "Schools"

    def __str__(self):
        return f"{self.name}"

MonEtabv1.4/src/user/forms/appSetting_form.py
from django import forms
from user.models.appSetting_model import AppSettingModel


class AppSettingForm(forms.ModelForm):
    class Meta:
        model = AppSettingModel
        fields = "__all__"
        

MonEtabv1.4/src/user/forms/roleUser_form.py
from django import forms
from user.models.roleUser_model import RoleUserModel


class RoleUserForm(forms.ModelForm):
    class Meta:
        model = RoleUserModel
        fields = "__all__"
        

MonEtabv1.4/src/user/forms/school_form.py
from django import forms
from user.models.school_model import SchoolModel


class SchoolForm(forms.ModelForm):
    class Meta:
        model = SchoolModel
        fields = "__all__"
        

MonEtabv1.4/src/user/forms/user_form.py
from django import forms
from user.models.custom_user_model import CustomUserModel


class UserFoms(forms.ModelForm):
    class Meta:
        model = CustomUserModel
        fields = [
            'username',
            'password',
            'roleUser',
            'school',
        ]
        

MonEtabv1.4/src/user/views/appSetting_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from user.forms.appSetting_form import AppSettingForm
from user.models.appSetting_model import AppSettingModel



def appS(request):

    if request.user.is_authenticated:
        return redirect('dashboard:index')

    context={"title":"App setting"}

    if request.method == "POST":
        print(request.POST)
        app_setting_form =AppSettingForm(request.POST)
        if app_setting_form.is_valid():
            print("form is valid")
            print(app_setting_form.cleaned_data)
            app_setting_form.save()
            return redirect('user:check_school')
        else:
            return render(request,"user/appSetting.html")

    app_setting_form = AppSettingForm()
    context["app_setting_form"] = app_setting_form

    app_setting  = AppSettingModel.objects.all()

    if not app_setting:
        return render(request,"user/appSetting.html",context)
    else:
        return redirect('user:school')



@login_required()
def edition_setting(request):

    app_setting = AppSettingModel.objects.first()

    context = {
        'title': 'Edit App Settings'
    }

    if request.method == "POST":
        print(request.POST)
        app_setting_form =AppSettingForm(request.POST, instance = app_setting)
        if app_setting_form.is_valid():
            print("form is valid")
            print(app_setting_form.cleaned_data)
            app_setting_form.save()
            return redirect('user:index_ap')
        else:
            return render(request,"user/appSetting.html")

    app_setting_form = AppSettingForm(instance = app_setting)
    context["app_setting_form"] = app_setting_form

    return render(request,"user/appSetting.html",context)




def check_setting(request):
    app_setting  = AppSettingModel.objects.all()

    if not app_setting:
        return redirect('user:appS')
    else:
        return redirect('user:check_school')

MonEtabv1.4/src/user/views/roleUser_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from user.forms.roleUser_form import RoleUserForm
from user.models.roleUser_model import RoleUserModel
from user.models.appSetting_model import AppSettingModel

def index_role(request):
    roles = RoleUserModel.objects.all()
    role_count = RoleUserModel.objects.count()
    context = {
        'roles':roles,
        'role_count':role_count
        
    }
    return render(request, "user/list_role.html", context)


def role(request):

    context={"title":"Ajout Role"}

    if request.method == "POST":
        print(request.POST)
        user_role_form =RoleUserForm(request.POST)
        context["user_role_form"] = user_role_form
        if user_role_form.is_valid():
            print("form is valid")
            print(user_role_form.cleaned_data)
            user_role_form.save()
            return redirect('user:check_user')
        else:
            return render(request,"user/roleUser.html")

    # context={'elev_form':elev_form}
    user_role_form = RoleUserForm()
    context["user_role_form"] = user_role_form

    role_users = RoleUserModel.objects.all()

    if not role_users:
        return render(request,"user/roleUser.html",context)
    else:
        return redirect('user:check_user')



def role_update(request, id):

    role_user = RoleUserModel.objects.get(id = id)

    context={"title":"Update Role"}

    if request.method == "POST":
        print(request.POST)
        user_role_form =RoleUserForm(request.POST, instance = role_user)
        context["user_role_form"] = user_role_form
        if user_role_form.is_valid():
            print("form is valid")
            print(user_role_form.cleaned_data)
            user_role_form.save()
            return redirect('user:index_role')
        else:
            return render(request,"user/roleUser.html")

    # context={'elev_form':elev_form}
    user_role_form = RoleUserForm(instance = role_user)
    
    context["user_role_form"] = user_role_form

    return render(request,"user/roleUser.html",context)


def check_role_user(request):

    role_users = RoleUserModel.objects.all()

    if not role_users:
        return redirect('user:role')
    else:
        return redirect('user:check_user')
    


def check_setting(request):
    app_setting  = AppSettingModel.objects.all()

    if not app_setting:
        return redirect('user:appS')
    else:
        return redirect('user:check_school')

MonEtabv1.4/src/user/views/school_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from user.forms.school_form import SchoolForm
from user.models.school_model import SchoolModel



def school(request):

    if request.user.is_authenticated:
        return redirect('dashboard:index')

    context = {
        "title": "School Setting"
    }

    if request.method == "POST":
        print(request.POST)
        form_school = SchoolForm(request.POST)
        context["form_school"] = form_school
        if form_school.is_valid():
            print("form is valid")
            print(form_school.cleaned_data)
            form_school.save()
            return redirect('user:check_role_user')
        else:
            return render(request,"user/school.html")

    # context={'elev_form':elev_form}
    form_school = SchoolForm()
    
    context['form_school'] = form_school

    schools = SchoolModel.objects.all()

    if not schools:
        return render(request,"user/school.html",context)
    else:
        return redirect('login:sign_in')



@login_required()
def edition(request):

    school = SchoolModel.objects.first()

    context = {
        'title': 'Edit School'
    }

    if request.method == 'POST':
        form_school = SchoolForm(request.POST, instance = school)
        if form_school.is_valid():
            form_school.save()
            return redirect('dashboard:index')
    else:
        form_school = SchoolForm(instance=school)

    context['form_school'] = form_school

    return render(request, 'user/school.html', context)



def check_school(request):
    schools = SchoolModel.objects.all()

    if not schools:
        return redirect('user:school')
    else:
        return redirect('user:check_role_user')

MonEtabv1.4/src/user/views/user_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from user.models.custom_user_model import CustomUserModel
from user.models.roleUser_model import RoleUserModel
from user.forms.user_form import UserFoms
from user.forms.roleUser_form import RoleUserForm


@login_required()
def index(request):

    search_field = request.GET.get('search')

    if search_field:
        users = CustomUserModel.objects.filter(username__icontains = search_field)

        context = {
            'users': users,
            'search_fields': search_field
        }
    else:     
        users = CustomUserModel.objects.all()
        print(users)
        user_count = CustomUserModel.objects.count()
        context = {
            'users':users,
            'user_count':user_count
        }
    return render(request, "user/index.html", context)



def add(request):
    context={"title":"Ajouter Utilisateur"}

    if request.method == "POST":
        print(request.POST)
        form = UserFoms(request.POST)
        if form.is_valid():
            print("form is valid")
            print(form.cleaned_data)
            form.save()
            # username = form.cleaned_data.get('username')
            # password = form.cleaned_data.get('password')
            # user = CustomUserModel(username = username)
            # user.save()

            # user.password = password
            # user.set_password(user.password)
            # user.save()

            return redirect('login:sign_in')            
        else:
            return render(request,"user/add.html")

    form = UserFoms()
    context = {
        'form': form
    }

    return render(request,"user/add.html",context)


@login_required()
def update(request, id):
    
    user = CustomUserModel.objects.get(id=id)
 
    context = {
        "title":"Modifier utilisateur"
    }

    if request.method == "POST":
        form = UserFoms(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user:index')
        
    form = UserFoms(instance = user)

    context["form"] = form

    return render(request,"user/add.html",context)



def sign_out(request):
    logout(request)
    return redirect('login:sign_in')


def check_user(request):

    users = CustomUserModel.objects.all()

    if users:
        return redirect('dashboard:index')
    else:
        return redirect('user:add')
    


def desable_user(request, id):
    user = get_object_or_404(CustomUserModel, id = id)
    user.is_active = False
    user.status = False
    user.save()
    return redirect('user:index')

MonEtabv1.4/src/templates/user/add.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - utilisateurs</title>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="bg-gray-100 font-sans antialiased">
    <div class="flex min-h-screen">
      <!-- Sidebar -->

      <!-- Main Content -->
      
      <div class="flex-1 p-6">
        
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}
    
             {{ form }}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>

    </div>
  </body>
</html>

MonEtabv1.4/src/templates/user/appSetting.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - utilisateurs</title>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="bg-gray-100 font-sans antialiased">
    <div class="flex min-h-screen">
      <!-- Sidebar -->

      <!-- Main Content -->
      
      <div class="flex-1 p-6">
        
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}
    
             {{ app_setting_form }}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>

    </div>
  </body>
</html>

MonEtabv1.4/src/templates/user/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<style>

  /* Styles pour le pop-up */
  .popup-overlay {
      display: none; /* Masqué par défaut */
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.5); /* Couleur de l'overlay */
      z-index: 1000; /* Au-dessus du contenu */
      justify-content: center;
      align-items: center;
  }
  
  .popup-content {
      background: white;
      padding: 20px;
      border-radius: 5px;
      text-align: center;
      position: relative; /* Positionnement relatif pour le pop-up */
      z-index: 1001; /* Au-dessus de l'overlay */
  }
  
  /* Appliquer le flou uniquement à l'arrière-plan */
  .blur {
      filter: blur(5px);
      position: relative;
      z-index: 999; /* Sous le pop-up */
  }
      
      
  </style>

<div class="flex-1 p-6">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-semibold">utilisateurs: {{ user_count }}</h1>
    <a href="{% url 'user:add' %}" class="flex items-center text-blue-500 hover:text-blue-700">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24"
        stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
      </svg>
      Nouvel utilisateur
    </a>
  </div>
  <div>
    <form get="GET" action="">
      <input type="text" value="{{ search_fields }}" placeholder="Rechercher....." name="search">
      <input type="submit" value="Rechercher">
    </form>
  </div> <br>
  <div class="bg-white p-6 rounded-lg shadow overflow-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Pseudo
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Date de création
          </th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for user in users %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">{{user.username}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{user.created_at}}</td>

          <td class="px-6 py-4 whitespace-nowrap">
            <a href="{% url 'user:update-user' user.id %}"
              class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded">
              Modifier
            </a> 
            <a href=""
              class="bg-green-500 hover:bg-red-600 text-white font-bold py-1 px-5 rounded">
              <button class="delete-button" onclick="confirmDelete(1)">Desactiver</button>
            </a>

          </td>
        </tr>


        <div id="confirmationPopup" class="popup-overlay">
          <div class="popup-content">
              <p>Êtes-vous sûr de vouloir supprimer cet élément ?</p>
              <a href="{% url 'user:desable_user' user.id %}">
                <button id="confirmButton">Oui</button>
              </a>
              <button id="cancelButton">Non</button>
          </div>
        </div>

        {% endfor %}

      </tbody>
    </table>
  </div>
</div>



<script>
    
  function confirmDelete() {
  // Prévenir le comportement par défaut du lien
  event.preventDefault();

  // Obtenir les éléments
  const popupOverlay = document.getElementById('confirmationPopup');
  const body = document.body;
  const deleteLink = document.getElementById('deleteLink');

  // Afficher le pop-up
  popupOverlay.style.display = 'flex'; // Affiche le pop-up
  //body.classList.add('blur'); // Applique le flou à l'arrière-plan

  // Gérer les boutons de confirmation
  // document.getElementById('confirmButton').onclick = function() {
  //     body.classList.remove('blur'); // Retirer le flou
  //     popupOverlay.style.display = 'none'; // Masquer le pop-up
  //     window.location.href = deleteLink.href; // Rediriger vers l'URL de suppression
  // };

  document.getElementById('cancelButton').onclick = function() {
      popupOverlay.style.display = 'none'; // Masquer le pop-up
      //body.classList.remove('blur'); // Retirer le flou
  };
}


</script>


{% endblock content %}

MonEtabv1.4/src/templates/user/list_app.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="flex-1 p-6">
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl font-semibold"> App Setting: {{ school_count }}</h1>
      <a
        href="{% url 'user:appS' %}"
        class="flex items-center text-blue-500 hover:text-blue-700"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5 mr-2"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 4v16m8-8H4"
          />
        </svg>
        Nouvelle App setting
      </a>
    </div>
    <div class="bg-white p-6 rounded-lg shadow overflow-auto">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th
              class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
            >
            App Setting username
            </th>
            <th
              class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
            >
            App Setting port
            </th>
            <th
            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
          >
            App Setting
          </th>
            <th
              class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
            >
              Actions
            </th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          {% for ap in aps %}
          <tr>
            <td class="px-6 py-4 whitespace-nowrap">{{ap.smtp_username}}</td>
            <td class="px-6 py-4 whitespace-nowrap">{{ap.smtp_port}}</td>
            <td class="px-6 py-4 whitespace-nowrap">{{ap.smtp_server}}</td>
            <td class="px-6 py-4 whitespace-nowrap">
              <a href="{% url 'user:app_setting_update' ap.id %}"
                class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
              >
                Modifier
            </a>
        </td>
      </tr>

      {% endfor %}
      
    </tbody>
  </table>
</div>
</div> 

{% endblock content %}

MonEtabv1.4/src/templates/user/list_role.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="flex-1 p-6">
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl font-semibold"> Role: {{ role_count }}</h1>
      <a
            href="{% url 'user:role' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouveau Role utilisateur
          </a>
    </div>
    <div class="bg-white p-6 rounded-lg shadow overflow-auto">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th
            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
          >
            Role
          </th>
            <th
              class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
            >
              Actions
            </th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          {% for role in roles %}
          <tr>
            <td class="px-6 py-4 whitespace-nowrap">{{role.role}}</td>
            
            <td class="px-6 py-4 whitespace-nowrap">
              <a href="{% url 'user:update_user_role' role.id %}"
                class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
              >
                Modifier
            </a>
            
        </td>
      </tr>

      {% endfor %}
      
    </tbody>
  </table>
</div>
</div> 

{% endblock content %}