MonEtabv1.4/src/EtabV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('student/', include("student.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('base/', include("base.urls")),
    path('login/', include('login.urls')),
    path('', include('api.urls')),
    path('report/', include('report.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

MonEtabv1.4/src/api/urls.py
from django.urls import path, include
from rest_framework import routers


from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from .viewsets.student_viewset import StudentViewset
from .viewsets.teacher_viewset import TeacherViewset
from .viewsets.appSetting_viewset import AppSettingViewset
from .viewsets.school_viewset import SchoolViewset
from .viewsets.role_user_viewset import Role_user_viewset
from .viewsets.student_card_viewset import StudentCardViewset
from .viewsets.absence_viewset import AbsenseViewset
from .viewsets.custom_user_viewset import CustomUserViewset
from .viewsets.address_viewset import Address_Viewset
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenObtainSlidingView,
    TokenRefreshSlidingView,
    TokenVerifyView,
)

app_name = 'api'


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'students', StudentViewset)
router.register(r'teachers', TeacherViewset)
router.register(r'AppSettings', AppSettingViewset)
router.register(r'school', SchoolViewset)
router.register(r'rolUser', Role_user_viewset)
router.register(r'studentCard', StudentCardViewset)
router.register(r'absence', AbsenseViewset)
router.register(r'customUser', CustomUserViewset)
router.register(r'Adress',Address_Viewset)



urlpatterns = [
    path('', include(router.urls)),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('token-sliding/', TokenObtainSlidingView.as_view(), name='token_obtain_sliding'),
    path('token-sliding/refresh/', TokenRefreshSlidingView.as_view(), name='token_refresh_sliding'),

    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
   
    
 ]

MonEtabv1.4/src/base/urls.py
from django.urls import path
from .views import add


app_name="adress"
urlpatterns = [
    path('add',add,name="add"),
    # path('update/<int:id>',update,name="update-student"),
    # path('delete/<int:id>',delete,name="delete-student"),
]

MonEtabv1.4/src/report/urls.py
from django.urls import path
from .views import check_setting, index, export



app_name = 'report'

urlpatterns = [
    path('', check_setting, name='check_setting'),
    path('index/', index, name='index'),
    path('generate/', export, name='generer')
]

MonEtabv1.4/src/student/urls.py
from django.urls import path
from .views.student_view import index,add, update, delete, check_setting
from .views.absence_view import add_abs,list_abs, update_abs 
from .views.studentCards_view import add_card, list_card, update_student_card



app_name="student"
urlpatterns = [

    path('', check_setting, name='check_setting'),

    path('index', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-student"),
    path('delete/<int:id>',delete,name="delete-student"),

    path('add_abs',add_abs,name="add_abs"),
    path('list_abs',list_abs,name="list_abs"),
    path('update_abs/<int:id>',update_abs,name="update_absence"),

    path('add_card',add_card,name="add_card"),
    path('list_card',list_card,name="list_card"),
    path('update_student_card/<int:id>', update_student_card, name='update_student_card')
]

MonEtabv1.4/src/teacher/urls.py
from django.urls import path
from .views import index, add, update, delete, check_setting



app_name="teacher"

urlpatterns = [
    path('', check_setting, name='check_setting'),
    path('index', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-teacher"),
    path('delete/<int:id>',delete,name="delete-teacher"),
]

MonEtabv1.4/src/user/urls.py
from django.urls import path
from .views.user_view import index, add, update, check_user, sign_out, desable_user
from .views.appSetting_view import  appS, check_setting, edition_setting
from .views.school_view import school, check_school, edition
from .views.roleUser_view import role, index_role, role_update, check_role_user


app_name="user"
urlpatterns = [

    path('', check_setting, name='check_setting'),

    path('dashboard/', index,name="index"),
    path('desable/<int:id>', desable_user, name='desable_user'),
    path('checkuser', check_user, name='check_user'),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-user"),

    path('checkschool', check_school, name='check_school'),
    path('school',school,name="school"),
    path('edition_school', edition, name='edition_school'),

    path('role',role,name="role"),
    path('checkroleuser', check_role_user, name='check_role_user'),
    path('index_role',index_role,name="index_role"),
    path('update_user_role/<int:id>',role_update, name='update_user_role'),
    

    path('appS',appS,name="appS"),
    path('edittion',edition_setting,name="edition_setting"),


    
    path('signout', sign_out, name='sign_out'),
    
    #path('delete/<int:id>',delete,name="delete-student"),
]

MonEtabv1.4/src/base/forms.py
from django import forms
from .models.helpers.adress_model import AdressModel

class AdressFoms(forms.ModelForm):
    class Meta:
        model = AdressModel
        fields = "__all__"
        

MonEtabv1.4/src/base/views.py
from django.shortcuts import render, redirect
from .forms import AdressFoms

# Create your views here.
def add(request):
    context={"title":"Ajouter Adress"}

    if request.method == "POST":
        print(request.POST)
        form =AdressFoms(request.POST)
        context["form"] = form
        if form.is_valid():
            print("form is valid")
            print(form.cleaned_data)
            form.save()
            return redirect('student:index')
        else:
            return render(request,"base/adress.html")

    # context={'elev_form':elev_form}
    form = AdressFoms()
    context["form"] = form

    return render(request,"base/adress.html",context)

MonEtabv1.4/src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - utilisateurs</title>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="bg-gray-100 font-sans antialiased">
    <div class="flex min-h-screen">
      <!-- Sidebar -->
      <aside class="w-64 bg-green-800 text-white flex flex-col justify-between">
        <div class="p-6">
          <h2 class="text-3xl font-semibold text-center mb-8">Mon Etab</h2>
          <nav>
            <ul>
              <li class="mb-4">
                <a href="{% url 'dashboard:index' %}" class="hover:text-gray-400">Dashboard</a>
              </li>
              <li>   
                <a
                  href="{% url 'student:index' %}"
                  class="text-blue-400 hover:text-blue-500 font-medium"
                  >Elève</a
                >
              </li>
              <li class="mb-4">
                <a href="{% url 'teacher:index' %}" class="hover:text-gray-400">Professeurs</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'user:index' %}" class="hover:text-gray-400">Utilisateurs</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'adress:add' %}" class="hover:text-gray-400">Adresse</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'user:edition_school' %}" class="hover:text-gray-400">Paramètre de l'ecole</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'user:index_role' %}" class="hover:text-gray-400">Role Utilisateur</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'user:edition_setting' %}" class="hover:text-gray-400">Paramètre de l'application</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'student:list_card' %}" class="hover:text-gray-400">Carte d'étudiant</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'student:list_abs' %}" class="hover:text-gray-400">Absence</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'report:index' %}" class="hover:text-gray-400">Rapport</a>
              </li>
            </ul>
          </nav>
        </div>
        <div class="p-6">
          <a
            href="{% url 'user:sign_out' %}"
            class="text-gray-400 hover:text-white flex items-center justify-center"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fill-rule="evenodd"
                d="M7 10V4a3 3 0 016 0v6a3 3 0 11-6 0z"
                clip-rule="evenodd"
              />
              <path
                fill-rule="evenodd"
                d="M5 9a2 2 0 100-4 2 2 0 000 4zm10-2a2 2 0 110 4 2 2 0 010-4zm-2 8v2a3 3 0 01-6 0v-2a2 2 0 11-4 0v2a5 5 0 0010 0v-2a2 2 0 11-4 0z"
                clip-rule="evenodd"
              />
            </svg>
            Déconnexion
          </a>
        </div>
      </aside>

      <!-- Main Content -->
      
      {% block content %}

      {% endblock content %}

    </div>
  </body>
</html>