MonEtabv1.4/src/EtabV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('student/', include("student.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('base/', include("base.urls")),
    path('login/', include('login.urls')),
    path('', include('api.urls')),
    path('report/', include('report.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

MonEtabv1.4/src/api/urls.py
from django.urls import path, include
from rest_framework import routers


from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from .viewsets.student_viewset import StudentViewset
from .viewsets.teacher_viewset import TeacherViewset
from .viewsets.appSetting_viewset import AppSettingViewset
from .viewsets.school_viewset import SchoolViewset
from .viewsets.role_user_viewset import Role_user_viewset
from .viewsets.student_card_viewset import StudentCardViewset
from .viewsets.absence_viewset import AbsenseViewset
from .viewsets.custom_user_viewset import CustomUserViewset
from .viewsets.address_viewset import Address_Viewset
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenObtainSlidingView,
    TokenRefreshSlidingView,
    TokenVerifyView,
)

app_name = 'api'


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = routers.DefaultRouter()
router.register(r'students', StudentViewset)
router.register(r'teachers', TeacherViewset)
router.register(r'AppSettings', AppSettingViewset)
router.register(r'school', SchoolViewset)
router.register(r'rolUser', Role_user_viewset)
router.register(r'studentCard', StudentCardViewset)
router.register(r'absence', AbsenseViewset)
router.register(r'customUser', CustomUserViewset)
router.register(r'Adress',Address_Viewset)



urlpatterns = [
    path('', include(router.urls)),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('token-sliding/', TokenObtainSlidingView.as_view(), name='token_obtain_sliding'),
    path('token-sliding/refresh/', TokenRefreshSlidingView.as_view(), name='token_refresh_sliding'),

    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
   
    
 ]

MonEtabv1.4/src/teacher/urls.py
from django.urls import path
from .views import index, add, update, delete, check_setting



app_name="teacher"

urlpatterns = [
    path('', check_setting, name='check_setting'),
    path('index', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-teacher"),
    path('delete/<int:id>',delete,name="delete-teacher"),
]

MonEtabv1.4/src/teacher/models/teacher_model.py
from django.db import models
from base.models.helpers.person_model import PersonModel



class TeacherModel(PersonModel):

    available = models.BooleanField(default=False)
    speciality = models.CharField(max_length=20)
    
    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "Teachers"

    def __str__(self):
        return self.last_name, self.speciality

MonEtabv1.4/src/teacher/forms.py
from django import forms
from teacher.models.teacher_model import TeacherModel
from base.models.helpers.person_model import PersonModel

class TeacherFoms(forms.ModelForm):
    class Meta:
        model = TeacherModel
        fields = "__all__"
        widgets={
            'birthday':forms.DateInput(attrs={'type':'date'}),
            'gender' :forms.RadioSelect(choices=PersonModel.GENDER_CHOICES),
        }

MonEtabv1.4/src/teacher/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import TeacherFoms
from user.models.appSetting_model import AppSettingModel
from .models.teacher_model import TeacherModel

# Create your views here.
@login_required
def index(request):

    search_field = request.GET.get('search')

    if search_field:

        teachers = TeacherModel.objects.filter(last_name__icontains = search_field)

        teacher_count = TeacherModel.objects.count()

        context = {
            'teachers': teachers,
            'teacher_count': teacher_count
        }
    else:
        teachers = TeacherModel.objects.all()
        teacher_count = TeacherModel.objects.count()
        context = {
            'teachers': teachers,
            'teacher_count': teacher_count
        }   
    return render(request, "teacher/index.html", context)


@login_required()
def add(request):
    context={"title":"Ajouter un eleve"}

    if request.method == "POST":
        print(request.POST)
        form = TeacherFoms(request.POST)
        context["form"] = form
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect('teacher:index')
        else:
            return render(request,"teacher/add.html")
    
    # context={'teach_form': teach_form}
    form = TeacherFoms()
    context["form"] = form

    return render(request,"teacher/add.html",context)


@login_required()
def update(request, id):
    teacher = TeacherModel.objects.get(id=id)

    context = {"title":"Modifier professeur"}

    if request.method == "POST":
        form = TeacherFoms(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('teacher:index')
        
    form = TeacherFoms(instance = teacher)

    context["form"] = form
    
    return render(request,"teacher/add.html",context)


@login_required()
def delete(request, id):
    teacher = TeacherModel.objects.get(id = id)
    teacher.delete()
    return redirect('teacher:index')



def check_setting(request):
    app_setting  = AppSettingModel.objects.all()

    if not app_setting:
        return redirect('user:appS')
    else:
        return redirect('user:check_school')

MonEtabv1.4/src/templates/teacher/add.html
{% extends 'base.html' %}


{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'teacher:index' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="#" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}
            
            {{form}}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <a
                href="{% url 'teacher:index' %}"
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </a>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}

MonEtabv1.4/src/templates/teacher/index.html
{% extends 'base.html' %}
{% load static %}

    

 
{% block content %}

      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">Professeur: {{ teacher_count }}</h1>
          <a
            href="{% url 'teacher:add' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouvel professeur
          </a>
        </div>
        <div>
          <form get="GET" action="">
            <input type="text" value="{{ search_fields }}" placeholder="Rechercher....." name="search">
            <input type="submit" value="Rechercher">
          </form>
        </div> <br>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date de Naissance
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Prénom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Telephone
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Url picture
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Genre
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Available
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Specialité
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Adresse
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  User
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for teacher in teachers %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.birthday}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.first_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.last_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.phone_number}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.url_picture}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.gender}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.available}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.speciality}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.adress.street}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.user.pseudo}}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <a
                  href="{% url 'teacher:update-teacher' teacher.id %}"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Modifier
                </a>
                  <button
                    class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded ml-2"
                  >
                  <a class="button" href="#popup{{teacher.id }}">Supprimer</a>
                  </button>
                </td>
                <div id="popup{{teacher.id }}" class="overlay">
                  <div class="popup">
                    <h2>ATTENTION !!!</h2>
                    <a class="close" href="#">&times;</a>
                    <div class="content">
                      Voulez-vous supprimer cet élève ?
                      <div>
                        <a href="#" class="bg-green-500 hover:bg-green-600 text-white font-bold py-1 px-4 rounded">Non</a>
                        <a href="{% url 'teacher:delete-teacher' teacher.id %}" class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded">Oui</a>
                      </div>
                      
                    </div>
                  </div>
                </div>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}